name: Security Test

on:
  push:
    paths-ignore:
      - 'cloud/**'
      - '.github/workflows/cloud_continuous_integration.yml'
      - '.github/workflow_scripts/test_cloud.sh'
  pull_request_target:
    paths-ignore:
      - 'cloud/**'
      - '.github/workflows/cloud_continuous_integration.yml'
      - '.github/workflow_scripts/test_cloud.sh'
  pull_request:
    paths-ignore:
      - 'cloud/**'
      - '.github/workflows/cloud_continuous_integration.yml'
      - '.github/workflow_scripts/test_cloud.sh'
permissions:
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  copy-docs:
    needs: build_all_docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Env Vars
        uses: tonyhoo/autogluon/.github/actions/setup-env-vars@6339c8cbddffebdbfac99134d933874062354a92
      - name: Copy Docs to Bucket(For push)
        if: ${{ github.event_name == 'push' }}
        run: |
          chmod +x ./.github/workflow_scripts/copy_docs.sh
          ./.github/workflow_scripts/copy_docs.sh '${{ github.ref }}' '${{ github.repository }}' '${{ env.SHORT_SHA }}'
      - name: Copy Docs to Bucket(For pull request)
        if: ${{ github.event_name == 'pull_request_target' }}
        env:
          branch: ${{ github.event.pull_request.head.ref }}
        run: |
          chmod +x ./.github/workflow_scripts/copy_docs.sh
          ./.github/workflow_scripts/copy_docs.sh "$branch" '${{ github.event.pull_request.head.repo.full_name }}' '${{ env.SHORT_SHA }}' PR-'${{ github.event.number }}'
     