name: Security Test

on:
  push:
    paths-ignore:
      - 'cloud/**'
      - '.github/workflows/cloud_continuous_integration.yml'
      - '.github/workflow_scripts/test_cloud.sh'
  pull_request_target:
    paths-ignore:
      - 'cloud/**'
      - '.github/workflows/cloud_continuous_integration.yml'
      - '.github/workflow_scripts/test_cloud.sh'
  pull_request:
    paths-ignore:
      - 'cloud/**'
      - '.github/workflows/cloud_continuous_integration.yml'
      - '.github/workflow_scripts/test_cloud.sh'
permissions:
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  build_multimodal_tutorial:
    strategy:
      matrix:
        SUB_DOC: ["advanced_topics", "image_prediction", "matching", "object_detectionm", "text_prediction", "multimodal_prediction"] 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Env Vars
        uses: ./.github/actions/setup-env-vars
      - name: Build Multimodal Tutorial on AWS Batch
        uses: ./.github/actions/submit-job
        with:
          job-type: CI-GPU
          job-name: AutoGluon-BuildMultimodal
          command: chmod +x ./.github/workflow_scripts/build_multimodal_tutorial.sh && ./.github/workflow_scripts/build_multimodal_tutorial.sh $SUB_DOC '${{ env.BRANCH }}' '${{ env.GIT_REPO }}' '${{ env.SHORT_SHA }}' '${{ env.PR_NUMBER }}'
